[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/auth",
    "crates/contract",
    "crates/rule-set",
    "crates/subscription",
    "crates/user",
    "crates/web",
]
default-members = [
    "crates/api",
    "crates/auth",
    "crates/contract",
    "crates/rule-set",
    "crates/subscription",
    "crates/user",
]
